# Makefile for lib-heron test
#
# This code is part of the Diderot Project (http://diderot-language.cs.uchicago.edu)
#
# COPYRIGHT (c) 2017 The University of Chicago
# All rights reserved.
#

TARGET		= simple

build:	$(TARGET)

include ../makedefs.gmk
include ../makerules.gmk

override DIDEROTC_FLAGS	+= --namespace=simple
